// ---------------------------------------------------------------------------
// @orbit/capability-core – Eight Domain Registry (Wave 2-C)
// ---------------------------------------------------------------------------

import type { CapabilityDefinition, CapabilityDomain } from './capability-interface.js';

export type { CapabilityDomain };

export interface DomainRegistry {
  register(definition: CapabilityDefinition): void;
  getByDomain(domain: CapabilityDomain): readonly CapabilityDefinition[];
  getById(id: string): CapabilityDefinition | null;
  getAll(): readonly CapabilityDefinition[];
  unregister(id: string): boolean;
  getDomains(): readonly CapabilityDomain[];
}

const ALL_DOMAINS: readonly CapabilityDomain[] = [
  'workspace_query',
  'content_capture',
  'research',
  'writing',
  'planning',
  'graph',
  'integration',
  'sensitive',
  'reader',
] as const;

export function createDomainRegistry(): DomainRegistry {
  const definitions = new Map<string, CapabilityDefinition>();

  const registry: DomainRegistry = {
    register(definition: CapabilityDefinition): void {
      if (definitions.has(definition.id)) {
        throw new Error(`Capability "${definition.id}" is already registered`);
      }
      if (!ALL_DOMAINS.includes(definition.domain)) {
        throw new Error(`Unknown domain "${definition.domain}"`);
      }
      definitions.set(definition.id, definition);
    },

    getByDomain(domain: CapabilityDomain): readonly CapabilityDefinition[] {
      return [...definitions.values()].filter((d) => d.domain === domain);
    },

    getById(id: string): CapabilityDefinition | null {
      return definitions.get(id) ?? null;
    },

    getAll(): readonly CapabilityDefinition[] {
      return [...definitions.values()];
    },

    unregister(id: string): boolean {
      return definitions.delete(id);
    },

    getDomains(): readonly CapabilityDomain[] {
      return ALL_DOMAINS;
    },
  };

  // Pre-populate with example capabilities for each domain
  const examples: readonly CapabilityDefinition[] = [
    {
      id: 'workspace_query.search',
      version: '1.0.0',
      domain: 'workspace_query',
      kind: 'search',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
      outputSchema: { type: 'array', items: { type: 'object' } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Full-text search across workspace objects',
      displayName: 'Workspace Search',
    },
    {
      id: 'content_capture.web_clip',
      version: '1.0.0',
      domain: 'content_capture',
      kind: 'import',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { url: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { content: { type: 'string' } } },
      risk: 'R2',
      approval: 'A1',
      audit: true,
      egress: 'metadata_only',
      description: 'Capture web page content as a workspace object',
      displayName: 'Web Clipper',
    },
    {
      id: 'research.summarize',
      version: '1.0.0',
      domain: 'research',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { text: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { summary: { type: 'string' } } },
      risk: 'R1',
      approval: 'A0',
      audit: true,
      egress: 'content_hash',
      description: 'Summarize text content using AI',
      displayName: 'AI Summarizer',
    },
    {
      id: 'writing.draft',
      version: '1.0.0',
      domain: 'writing',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { prompt: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { text: { type: 'string' } } },
      risk: 'R1',
      approval: 'A1',
      audit: true,
      egress: 'none',
      description: 'Generate draft content from a prompt',
      displayName: 'Draft Writer',
    },
    {
      id: 'planning.create_task',
      version: '1.0.0',
      domain: 'planning',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { title: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { taskId: { type: 'string' } } },
      risk: 'R1',
      approval: 'A1',
      audit: true,
      egress: 'none',
      description: 'Create a new planning task',
      displayName: 'Task Creator',
    },
    {
      id: 'graph.traverse',
      version: '1.0.0',
      domain: 'graph',
      kind: 'search',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { rootId: { type: 'string' }, depth: { type: 'number' } } },
      outputSchema: { type: 'array', items: { type: 'object' } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Traverse the object graph from a root node',
      displayName: 'Graph Traversal',
    },
    {
      id: 'integration.webhook',
      version: '1.0.0',
      domain: 'integration',
      kind: 'export',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { url: { type: 'string' }, payload: { type: 'object' } } },
      outputSchema: { type: 'object', properties: { statusCode: { type: 'number' } } },
      risk: 'R3',
      approval: 'A2',
      audit: true,
      egress: 'full_content',
      description: 'Send data to an external webhook endpoint',
      displayName: 'Webhook Sender',
    },
    {
      id: 'sensitive.encrypt',
      version: '1.0.0',
      domain: 'sensitive',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { data: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { encrypted: { type: 'string' } } },
      risk: 'R3',
      approval: 'A3',
      audit: true,
      egress: 'none',
      description: 'Encrypt sensitive data for storage',
      displayName: 'Data Encryptor',
    },

    // ---- Reader domain: Subscription & Resolution ----

    {
      id: 'reader.resolve_url',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { url: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { type: { type: 'string' }, resolved: { type: 'object' } } },
      risk: 'R1',
      approval: 'A0',
      audit: true,
      egress: 'metadata_only',
      description: 'Resolve any URL to identify its type (YouTube, Podcast, RSS, Newsletter, etc.)',
      displayName: 'URL Resolver',
    },
    {
      id: 'reader.discover_rss_feeds',
      version: '1.0.0',
      domain: 'reader',
      kind: 'search',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { url: { type: 'string' } } },
      outputSchema: { type: 'array', items: { type: 'object' } },
      risk: 'R1',
      approval: 'A0',
      audit: true,
      egress: 'metadata_only',
      description: 'Discover RSS/Atom feeds from a web page',
      displayName: 'RSS Feed Discoverer',
    },
    {
      id: 'reader.parse_rss_feed',
      version: '1.0.0',
      domain: 'reader',
      kind: 'import',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { url: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { entries: { type: 'array' } } },
      risk: 'R1',
      approval: 'A0',
      audit: true,
      egress: 'content_hash',
      description: 'Parse RSS/Atom XML into structured entries',
      displayName: 'RSS Feed Parser',
    },
    {
      id: 'reader.parse_opml',
      version: '1.0.0',
      domain: 'reader',
      kind: 'import',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { xml: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { subscriptions: { type: 'array' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Import OPML subscription lists',
      displayName: 'OPML Importer',
    },
    {
      id: 'reader.export_opml',
      version: '1.0.0',
      domain: 'reader',
      kind: 'export',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { subscriptionIds: { type: 'array' } } },
      outputSchema: { type: 'object', properties: { xml: { type: 'string' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'metadata_only',
      description: 'Export subscriptions as OPML',
      displayName: 'OPML Exporter',
    },
    {
      id: 'reader.resolve_youtube',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { url: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { videoId: { type: 'string' }, channelId: { type: 'string' }, kind: { type: 'string' } } },
      risk: 'R2',
      approval: 'A0',
      audit: true,
      egress: 'metadata_only',
      description: 'Resolve YouTube URLs (video vs channel detection)',
      displayName: 'YouTube Resolver',
    },
    {
      id: 'reader.resolve_podcast',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { url: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { feedUrl: { type: 'string' }, platform: { type: 'string' } } },
      risk: 'R2',
      approval: 'A0',
      audit: true,
      egress: 'metadata_only',
      description: 'Resolve podcast URLs (Apple, Spotify, 小宇宙)',
      displayName: 'Podcast Resolver',
    },

    // ---- Reader domain: Content Processing ----

    {
      id: 'reader.determine_processing_depth',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { objectId: { type: 'string' }, origin: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { depth: { type: 'string' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Decide processing depth based on origin and link density',
      displayName: 'Processing Depth Analyzer',
    },
    {
      id: 'reader.build_pipeline_steps',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { depth: { type: 'string' }, contentType: { type: 'string' } } },
      outputSchema: { type: 'array', items: { type: 'object' } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Build processing pipeline based on depth',
      displayName: 'Pipeline Builder',
    },
    {
      id: 'reader.schedule_fetch',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { endpointId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { nextFetchAt: { type: 'string' } } },
      risk: 'R1',
      approval: 'A0',
      audit: true,
      egress: 'none',
      description: 'Compute next fetch schedule for endpoints',
      displayName: 'Fetch Scheduler',
    },
    {
      id: 'reader.select_due_endpoints',
      version: '1.0.0',
      domain: 'reader',
      kind: 'search',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { now: { type: 'string' } } },
      outputSchema: { type: 'array', items: { type: 'object' } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Select endpoints due for fetching',
      displayName: 'Due Endpoint Selector',
    },
    {
      id: 'reader.compute_adaptive_interval',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { endpointId: { type: 'string' }, history: { type: 'array' } } },
      outputSchema: { type: 'object', properties: { intervalMs: { type: 'number' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Compute adaptive fetch intervals',
      displayName: 'Adaptive Interval Calculator',
    },

    // ---- Reader domain: Rendering ----

    {
      id: 'reader.render_video',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { videoId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { state: { type: 'object' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Create and manage video reader state',
      displayName: 'Video Renderer',
    },
    {
      id: 'reader.render_podcast',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { episodeId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { state: { type: 'object' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Create and manage podcast reader state',
      displayName: 'Podcast Renderer',
    },
    {
      id: 'reader.sync_video_transcript',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { videoId: { type: 'string' }, currentTime: { type: 'number' } } },
      outputSchema: { type: 'object', properties: { segments: { type: 'array' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Sync video playback with transcript',
      displayName: 'Video Transcript Sync',
    },
    {
      id: 'reader.map_podcast_speakers',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { episodeId: { type: 'string' }, speakerIds: { type: 'array' } } },
      outputSchema: { type: 'object', properties: { speakerMap: { type: 'object' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Map podcast speaker identifiers to names',
      displayName: 'Podcast Speaker Mapper',
    },

    // ---- Reader domain: Highlights & Selection ----

    {
      id: 'reader.highlight_create',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { objectId: { type: 'string' }, selectedText: { type: 'string' }, anchorData: { type: 'object' } } },
      outputSchema: { type: 'object', properties: { highlightId: { type: 'string' }, anchorPayload: { type: 'object' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Create a highlight with 4-layer anchor payload',
      displayName: 'Highlight Creator',
    },
    {
      id: 'reader.highlight_list',
      version: '1.0.0',
      domain: 'reader',
      kind: 'search',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { objectId: { type: 'string' }, filters: { type: 'object' } } },
      outputSchema: { type: 'object', properties: { highlights: { type: 'array' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'List highlights for an object',
      displayName: 'Highlight Lister',
    },
    {
      id: 'reader.highlight_resolve',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { highlightIds: { type: 'array' }, currentText: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { resolutions: { type: 'array' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Resolve highlight anchors in updated content',
      displayName: 'Highlight Resolver',
    },
    {
      id: 'reader.selection_capture',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { text: { type: 'string' }, anchorData: { type: 'object' }, source: { type: 'string' }, sourceId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { selectionContext: { type: 'object' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Capture a text selection context',
      displayName: 'Selection Capturer',
    },
    {
      id: 'reader.anchor_resolve',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { anchor: { type: 'object' }, currentText: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { found: { type: 'boolean' }, state: { type: 'string' }, confidence: { type: 'number' }, method: { type: 'string' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Resolve a single anchor in text',
      displayName: 'Anchor Resolver',
    },

    // ---- Reader domain: Notes ----

    {
      id: 'reader.note_create',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { content: { type: 'string' }, linkedHighlightId: { type: 'string' }, sourceId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { noteId: { type: 'string' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Create a note linked to a highlight or selection',
      displayName: 'Note Creator',
    },
    {
      id: 'reader.note_list',
      version: '1.0.0',
      domain: 'reader',
      kind: 'search',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { objectId: { type: 'string' }, filters: { type: 'object' } } },
      outputSchema: { type: 'object', properties: { notes: { type: 'array' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'List notes for an object',
      displayName: 'Note Lister',
    },

    // ---- Reader domain: Transcription ----

    {
      id: 'reader.start_transcription',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { audioSource: { type: 'string' }, providerId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { jobId: { type: 'string' }, status: { type: 'string' } } },
      risk: 'R2',
      approval: 'A1',
      audit: true,
      egress: 'content_hash',
      description: 'Start audio transcription job',
      displayName: 'Transcription Starter',
    },
    {
      id: 'reader.get_transcription_status',
      version: '1.0.0',
      domain: 'reader',
      kind: 'search',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { jobId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { state: { type: 'string' }, progress: { type: 'number' }, transcript: { type: 'string' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Check transcription job status',
      displayName: 'Transcription Status Checker',
    },
    {
      id: 'reader.cancel_transcription',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { jobId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { cancelled: { type: 'boolean' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Cancel a running transcription',
      displayName: 'Transcription Canceller',
    },

    // ---- Reader domain: Translation ----

    {
      id: 'reader.start_translation',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { texts: { type: 'array' }, sourceLanguage: { type: 'string' }, targetLanguage: { type: 'string' }, engineId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { translations: { type: 'array' }, detectedLanguage: { type: 'string' } } },
      risk: 'R2',
      approval: 'A1',
      audit: true,
      egress: 'full_content',
      description: 'Translate content',
      displayName: 'Translation Starter',
    },
    {
      id: 'reader.detect_language',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { text: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { language: { type: 'string' }, confidence: { type: 'number' } } },
      risk: 'R1',
      approval: 'A0',
      audit: false,
      egress: 'metadata_only',
      description: 'Detect text language',
      displayName: 'Language Detector',
    },
    {
      id: 'reader.build_bilingual_view',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { paragraphs: { type: 'array' }, translationPairs: { type: 'array' } } },
      outputSchema: { type: 'object', properties: { bilingualParagraphs: { type: 'array' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Build bilingual paragraph view',
      displayName: 'Bilingual View Builder',
    },

    // ---- Reader domain: Pipeline ----

    {
      id: 'reader.run_pipeline',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'external',
      inputSchema: { type: 'object', properties: { url: { type: 'string' }, retryPolicy: { type: 'object' } } },
      outputSchema: { type: 'object', properties: { pipelineResult: { type: 'object' } } },
      risk: 'R2',
      approval: 'A1',
      audit: true,
      egress: 'content_hash',
      description: 'Run the full content pipeline on a URL',
      displayName: 'Pipeline Runner',
    },
    {
      id: 'reader.extract_audio',
      version: '1.0.0',
      domain: 'reader',
      kind: 'agent',
      exposure: 'local',
      inputSchema: { type: 'object', properties: { videoPath: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { audioPath: { type: 'string' }, duration: { type: 'number' }, format: { type: 'string' } } },
      risk: 'R1',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Extract audio from video file',
      displayName: 'Audio Extractor',
    },

    // ---- Graph domain: Object Graph extensions ----

    {
      id: 'graph.compute_link_density',
      version: '1.0.0',
      domain: 'graph',
      kind: 'search',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { objectId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { density: { type: 'number' }, inbound: { type: 'number' }, outbound: { type: 'number' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Compute link density metrics for an object',
      displayName: 'Link Density Calculator',
    },
    {
      id: 'graph.compute_feed_priority',
      version: '1.0.0',
      domain: 'graph',
      kind: 'search',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { feedId: { type: 'string' } } },
      outputSchema: { type: 'object', properties: { priority: { type: 'number' }, factors: { type: 'object' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Compute feed priority score',
      displayName: 'Feed Priority Calculator',
    },
    {
      id: 'graph.decide_link_activation',
      version: '1.0.0',
      domain: 'graph',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { linkId: { type: 'string' }, context: { type: 'object' } } },
      outputSchema: { type: 'object', properties: { action: { type: 'string' }, reason: { type: 'string' } } },
      risk: 'R1',
      approval: 'A1',
      audit: true,
      egress: 'none',
      description: 'Decide whether to auto-activate, propose, or discard a link suggestion',
      displayName: 'Link Activation Decider',
    },
    {
      id: 'graph.evaluate_activation_policy',
      version: '1.0.0',
      domain: 'graph',
      kind: 'agent',
      exposure: 'internal',
      inputSchema: { type: 'object', properties: { linkId: { type: 'string' }, policy: { type: 'object' } } },
      outputSchema: { type: 'object', properties: { allowed: { type: 'boolean' }, reason: { type: 'string' } } },
      risk: 'R0',
      approval: 'A0',
      audit: false,
      egress: 'none',
      description: 'Evaluate link activation policy',
      displayName: 'Activation Policy Evaluator',
    },
  ];

  for (const example of examples) {
    definitions.set(example.id, example);
  }

  return registry;
}
