/**
 * YouTube video metadata, details, transcript, and channel feed resolution.
 * Migrated and adapted from old-orbit/src/main/services/youtube-service.ts
 * for browser-safe fetch + HTML parsing.
 */

import type { FetchFn, FetchPageOptions } from './fetch-helpers.js';
import { fetchJson, fetchPageHtml, BROWSER_UA } from './fetch-helpers.js';

// ── Public types ───────────────────────────────────────────

export interface YouTubeVideoMeta {
  readonly title: string;
  readonly author: string | null;
  readonly thumbnail: string;
  readonly duration: number | null;
}

export interface YouTubeComment {
  readonly author: string;
  readonly authorThumbnail: string | null;
  readonly text: string;
  readonly likeCount: number | null;
  readonly publishedText: string | null;
}

export interface YouTubeVideoDetails {
  readonly title: string | null;
  readonly description: string | null;
  readonly viewCount: number | null;
  readonly likeCount: number | null;
  readonly commentCount: number | null;
  readonly uploadDate: string | null;
  readonly channelName: string | null;
  readonly channelThumbnail: string | null;
  readonly subscriberCount: string | null;
  readonly duration: number | null;
  readonly thumbnail: string | null;
  readonly comments: readonly YouTubeComment[];
}

export interface YouTubeTranscriptSegment {
  readonly startTime: number;
  readonly endTime: number;
  readonly text: string;
}

export interface YouTubeTranscript {
  readonly language: string | null;
  readonly isAutoGenerated: boolean;
  readonly segments: readonly YouTubeTranscriptSegment[];
}

interface WatchPageSnapshot {
  readonly html: string;
  readonly playerResponse: Record<string, unknown> | null;
  readonly initialData: Record<string, unknown> | null;
}

interface CaptionTrack {
  readonly baseUrl: string;
  readonly languageCode: string | null;
  readonly kind: string | null;
}

const WATCH_PAGE_CACHE_TTL_MS = 10 * 60 * 1000;
const watchPageCache = new Map<string, { timestamp: number; snapshot: WatchPageSnapshot }>();
const CJK_PATTERN = /[\u4e00-\u9fff\u3400-\u4dbf\u3000-\u303f\uff00-\uffef]/;

// ── Video Metadata (oEmbed + watch page duration fallback) ──

/**
 * Fetch YouTube video metadata via the oEmbed API (no API key required),
 * with watch-page parsing as a duration fallback.
 */
export async function fetchYouTubeVideoMeta(
  videoId: string,
  options?: FetchPageOptions,
): Promise<YouTubeVideoMeta | null> {
  const oembedUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;

  const [data, snapshot] = await Promise.all([
    fetchJson<{
      title?: string;
      author_name?: string;
    }>(oembedUrl, options),
    loadWatchPageSnapshot(videoId, options),
  ]);

  if (!data && !snapshot) return null;

  const duration = extractDuration(snapshot?.playerResponse ?? null);
  const thumbnail =
    extractThumbnailUrl(getNested(snapshot?.playerResponse ?? null, 'videoDetails', 'thumbnail')) ??
    `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;

  return {
    title:
      data?.title ??
      stringValue(getNested(snapshot?.playerResponse ?? null, 'videoDetails', 'title')) ??
      videoId,
    author:
      data?.author_name ??
      stringValue(getNested(snapshot?.playerResponse ?? null, 'videoDetails', 'author')),
    thumbnail,
    duration,
  };
}

// ── Full video details ──────────────────────────────────────

export async function fetchYouTubeVideoDetails(
  videoId: string,
  options?: FetchPageOptions,
): Promise<YouTubeVideoDetails | null> {
  const snapshot = await loadWatchPageSnapshot(videoId, options);
  if (!snapshot?.playerResponse) return null;

  const videoDetails = asRecord(getNested(snapshot.playerResponse, 'videoDetails'));
  const microformat = asRecord(
    getNested(snapshot.playerResponse, 'microformat', 'playerMicroformatRenderer'),
  );
  const owner = asRecord(findFirstNodeByKey(snapshot.initialData, 'videoOwnerRenderer'));
  const comments = extractComments(snapshot.initialData);

  const title =
    stringValue(videoDetails?.title) ?? null;
  const description =
    stringValue(videoDetails?.shortDescription) ??
    stringValue(microformat?.description) ??
    null;
  const uploadDate =
    stringValue(microformat?.uploadDate) ??
    stringValue(microformat?.publishDate) ??
    null;
  const channelName =
    textValue(getNested(owner, 'title')) ??
    stringValue(videoDetails?.author) ??
    null;
  const channelThumbnail = extractThumbnailUrl(getNested(owner, 'thumbnail'));
  const subscriberCount = textValue(getNested(owner, 'subscriberCountText'));
  const viewCount =
    parseCount(videoDetails?.viewCount) ??
    parseCount(microformat?.viewCount) ??
    null;
  const likeCount = extractLikeCount(snapshot.initialData);
  const commentCount =
    extractCommentCount(snapshot.initialData) ??
    (comments.length > 0 ? comments.length : null);
  const duration = extractDuration(snapshot.playerResponse);
  const thumbnail = extractThumbnailUrl(videoDetails?.thumbnail);

  return {
    title,
    description,
    viewCount,
    likeCount,
    commentCount,
    uploadDate,
    channelName,
    channelThumbnail,
    subscriberCount,
    duration,
    thumbnail,
    comments,
  };
}

// ── Transcript ──────────────────────────────────────────────

export async function fetchYouTubeTranscript(
  videoId: string,
  options?: FetchPageOptions,
): Promise<YouTubeTranscript | null> {
  const snapshot = await loadWatchPageSnapshot(videoId, options);
  if (!snapshot?.playerResponse) return null;

  const title =
    stringValue(getNested(snapshot.playerResponse, 'videoDetails', 'title')) ?? '';
  const captionTrack = selectCaptionTrack(snapshot.playerResponse, title);
  if (!captionTrack) return null;

  const timedTextUrl = ensureJson3CaptionUrl(captionTrack.baseUrl);
  const payload = await fetchRawJson<{ events?: Array<Record<string, unknown>> }>(
    timedTextUrl,
    options,
  );
  if (!payload?.events) return null;

  const segments = parseTranscriptSegments(payload.events);
  if (segments.length === 0) return null;

  return {
    language: captionTrack.languageCode,
    isAutoGenerated: captionTrack.kind === 'asr',
    segments,
  };
}

// ── Channel Feed Resolution ────────────────────────────────

/**
 * Resolve a YouTube channel/handle URL to its RSS feed URL.
 * Fetches the channel page HTML and extracts the channel ID.
 */
export async function resolveYouTubeChannelFeed(
  url: string,
  options?: FetchPageOptions,
): Promise<string | null> {
  const html = await fetchPageHtml(url, {
    ...options,
    userAgent: options?.userAgent ?? BROWSER_UA,
  });
  if (!html) return null;

  const metaMatch = html.match(/<meta\s+itemprop="channelId"\s+content="([^"]+)"/);
  if (metaMatch) {
    return `https://www.youtube.com/feeds/videos.xml?channel_id=${metaMatch[1]}`;
  }

  const canonicalMatch = html.match(
    /https:\/\/www\.youtube\.com\/channel\/(UC[a-zA-Z0-9_-]+)/,
  );
  if (canonicalMatch) {
    return `https://www.youtube.com/feeds/videos.xml?channel_id=${canonicalMatch[1]}`;
  }

  const rssMatch = html.match(
    /<link[^>]+type="application\/rss\+xml"[^>]+href="([^"]+)"/,
  );
  if (rssMatch) {
    return rssMatch[1];
  }

  return null;
}

// ── Shared watch-page parsing ───────────────────────────────

async function loadWatchPageSnapshot(
  videoId: string,
  options?: FetchPageOptions,
): Promise<WatchPageSnapshot | null> {
  const cached = watchPageCache.get(videoId);
  if (cached && Date.now() - cached.timestamp < WATCH_PAGE_CACHE_TTL_MS) {
    return cached.snapshot;
  }

  const html = await fetchPageHtml(`https://www.youtube.com/watch?v=${videoId}`, {
    ...options,
    userAgent: options?.userAgent ?? BROWSER_UA,
  });
  if (!html) return null;

  const snapshot: WatchPageSnapshot = {
    html,
    playerResponse: extractEmbeddedJson(html, [
      'var ytInitialPlayerResponse = ',
      'ytInitialPlayerResponse = ',
      'window["ytInitialPlayerResponse"] = ',
    ]),
    initialData: extractEmbeddedJson(html, [
      'var ytInitialData = ',
      'ytInitialData = ',
      'window["ytInitialData"] = ',
    ]),
  };

  watchPageCache.set(videoId, { timestamp: Date.now(), snapshot });
  return snapshot;
}

function extractEmbeddedJson(
  html: string,
  markers: readonly string[],
): Record<string, unknown> | null {
  for (const marker of markers) {
    const markerIndex = html.indexOf(marker);
    if (markerIndex === -1) continue;

    const jsonStart = html.indexOf('{', markerIndex + marker.length);
    if (jsonStart === -1) continue;

    const jsonString = extractBalancedObject(html, jsonStart);
    if (!jsonString) continue;

    try {
      const parsed = JSON.parse(jsonString) as unknown;
      const record = asRecord(parsed);
      if (record) return record;
    } catch {
      continue;
    }
  }

  return null;
}

function extractBalancedObject(input: string, startIndex: number): string | null {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = startIndex; index < input.length; index += 1) {
    const char = input[index];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === '\\') {
        escaped = true;
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === '{') {
      depth += 1;
    } else if (char === '}') {
      depth -= 1;
      if (depth === 0) {
        return input.slice(startIndex, index + 1);
      }
    }
  }

  return null;
}

// ── Transcript helpers ──────────────────────────────────────

function selectCaptionTrack(
  playerResponse: Record<string, unknown>,
  title: string,
): CaptionTrack | null {
  const rawTracks = getNested(
    playerResponse,
    'captions',
    'playerCaptionsTracklistRenderer',
    'captionTracks',
  );

  if (!Array.isArray(rawTracks) || rawTracks.length === 0) return null;

  const tracks: CaptionTrack[] = rawTracks
    .map((track) => {
      const record = asRecord(track);
      if (!record) return null;
      const baseUrl = stringValue(record.baseUrl);
      if (!baseUrl) return null;
      return {
        baseUrl,
        languageCode: stringValue(record.languageCode),
        kind: stringValue(record.kind),
      } satisfies CaptionTrack;
    })
    .filter((track): track is CaptionTrack => track != null);

  if (tracks.length === 0) return null;

  const prefersChinese = CJK_PATTERN.test(title);
  const preferredLanguages = prefersChinese
    ? ['zh-Hans', 'zh-CN', 'zh', 'zh-Hant', 'zh-TW', 'en', 'en-US']
    : ['en', 'en-US', 'en-GB', 'zh-Hans', 'zh-CN', 'zh'];

  const manualTracks = tracks.filter((track) => track.kind !== 'asr');
  const autoTracks = tracks.filter((track) => track.kind === 'asr');

  for (const language of preferredLanguages) {
    const manual = manualTracks.find((track) => track.languageCode === language);
    if (manual) return manual;
  }
  for (const language of preferredLanguages) {
    const auto = autoTracks.find((track) => track.languageCode === language);
    if (auto) return auto;
  }

  return manualTracks[0] ?? autoTracks[0] ?? null;
}

function ensureJson3CaptionUrl(baseUrl: string): string {
  try {
    const url = new URL(baseUrl);
    url.searchParams.set('fmt', 'json3');
    return url.toString();
  } catch {
    return baseUrl;
  }
}

function parseTranscriptSegments(
  events: readonly Record<string, unknown>[],
): YouTubeTranscriptSegment[] {
  const segments: YouTubeTranscriptSegment[] = [];

  for (const event of events) {
    const startMs = numberValue(event.tStartMs);
    if (startMs == null) continue;

    const segs = Array.isArray(event.segs) ? event.segs : [];
    const text = segs
      .map((segment) => {
        const record = asRecord(segment);
        return typeof record?.utf8 === 'string' ? record.utf8 : '';
      })
      .join('')
      .replace(/\s+/g, ' ')
      .trim();

    if (!text || text === '\n') continue;

    const durationMs = numberValue(event.dDurationMs) ?? 0;
    segments.push({
      startTime: startMs / 1000,
      endTime: (startMs + durationMs) / 1000,
      text,
    });
  }

  return segments;
}

// ── Details helpers ─────────────────────────────────────────

function extractComments(initialData: Record<string, unknown> | null): YouTubeComment[] {
  const comments = collectNodesByKey(initialData, 'commentRenderer')
    .map((value) => asRecord(value))
    .filter((value): value is Record<string, unknown> => value != null)
    .map((renderer) => {
      const author = textValue(renderer.authorText) ?? '未知用户';
      const text = textValue(renderer.contentText) ?? '';
      if (!text) return null;

      return {
        author,
        authorThumbnail: extractThumbnailUrl(renderer.authorThumbnail),
        text,
        likeCount: parseCount(renderer.voteCount),
        publishedText: textValue(renderer.publishedTimeText),
      } satisfies YouTubeComment;
    })
    .filter((comment): comment is YouTubeComment => comment != null);

  return dedupeComments(comments).slice(0, 20);
}

function dedupeComments(comments: readonly YouTubeComment[]): YouTubeComment[] {
  const seen = new Set<string>();
  const result: YouTubeComment[] = [];

  for (const comment of comments) {
    const key = `${comment.author}::${comment.text}`;
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(comment);
  }

  return result;
}

function extractCommentCount(initialData: Record<string, unknown> | null): number | null {
  const header = asRecord(findFirstNodeByKey(initialData, 'commentsHeaderRenderer'));
  return parseCount(header?.countText ?? header?.commentsCount);
}

function extractLikeCount(initialData: Record<string, unknown> | null): number | null {
  const toggleButtons = collectNodesByKey(initialData, 'toggleButtonRenderer')
    .map((value) => asRecord(value))
    .filter((value): value is Record<string, unknown> => value != null);

  for (const button of toggleButtons) {
    const targetId = stringValue(button.targetId) ?? '';
    const label =
      textValue(getNested(button, 'defaultText')) ??
      textValue(getNested(button, 'defaultTooltip')) ??
      textValue(getNested(button, 'accessibility', 'label')) ??
      '';

    if (!/like/i.test(targetId) && !/like/i.test(label)) continue;
    const count =
      parseCount(getNested(button, 'defaultText')) ??
      parseCount(label);
    if (count != null) return count;
  }

  return null;
}

function extractDuration(playerResponse: Record<string, unknown> | null): number | null {
  return parseCount(getNested(playerResponse, 'videoDetails', 'lengthSeconds'));
}

// ── Generic parsing helpers ─────────────────────────────────

async function fetchRawJson<T = unknown>(
  url: string,
  options?: FetchPageOptions,
): Promise<T | null> {
  const doFetch: FetchFn = options?.fetchFn ?? globalThis.fetch;

  try {
    const response = await doFetch(url, {
      headers: {
        'User-Agent': options?.userAgent ?? BROWSER_UA,
        Accept: 'application/json,text/plain,*/*',
      },
      signal: AbortSignal.timeout(options?.timeoutMs ?? 15_000),
      redirect: 'follow',
    });

    if (!response.ok) return null;
    return (await response.json()) as T;
  } catch {
    return null;
  }
}

function collectNodesByKey(value: unknown, key: string): unknown[] {
  const matches: unknown[] = [];
  walkNode(value, (record) => {
    if (record[key] !== undefined) {
      matches.push(record[key]);
    }
  });
  return matches;
}

function findFirstNodeByKey(value: unknown, key: string): unknown | null {
  let match: unknown | null = null;
  walkNode(value, (record) => {
    if (match == null && record[key] !== undefined) {
      match = record[key];
    }
  });
  return match;
}

function walkNode(
  value: unknown,
  visitor: (record: Record<string, unknown>) => void,
): void {
  if (Array.isArray(value)) {
    for (const item of value) {
      walkNode(item, visitor);
    }
    return;
  }

  const record = asRecord(value);
  if (!record) return;

  visitor(record);
  for (const child of Object.values(record)) {
    walkNode(child, visitor);
  }
}

function asRecord(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function getNested(value: unknown, ...path: readonly string[]): unknown {
  let current: unknown = value;

  for (const key of path) {
    const record = asRecord(current);
    if (!record) return null;
    current = record[key];
  }

  return current ?? null;
}

function stringValue(value: unknown): string | null {
  return typeof value === 'string' && value.trim() ? value.trim() : null;
}

function numberValue(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim()) {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
}

function textValue(value: unknown): string | null {
  if (typeof value === 'string') return value.trim() || null;
  if (Array.isArray(value)) {
    const joined = value.map(textValue).filter(Boolean).join('');
    return joined.trim() || null;
  }

  const record = asRecord(value);
  if (!record) return null;

  if (typeof record.simpleText === 'string') {
    return record.simpleText.trim() || null;
  }

  if (Array.isArray(record.runs)) {
    const joined = record.runs
      .map((run) => textValue(run))
      .filter((part): part is string => Boolean(part))
      .join('');
    return joined.trim() || null;
  }

  if (typeof record.text === 'string') {
    return record.text.trim() || null;
  }

  return null;
}

function extractThumbnailUrl(value: unknown): string | null {
  if (Array.isArray(value)) {
    const thumbnails = value
      .map((item) => asRecord(item))
      .filter((item): item is Record<string, unknown> => item != null)
      .map((item) => stringValue(item.url))
      .filter((url): url is string => url != null);
    return thumbnails.at(-1) ?? null;
  }

  const thumbnails = getNested(value, 'thumbnails');
  return Array.isArray(thumbnails) ? extractThumbnailUrl(thumbnails) : null;
}

function parseCount(value: unknown): number | null {
  const raw = textValue(value) ?? stringValue(value);
  if (!raw) return null;

  const normalized = raw.replace(/,/g, '').replace(/\s+/g, '').toLowerCase();
  const plain = normalized.match(/^\d+$/);
  if (plain) return Number(plain[0]);

  const compact = normalized.match(/([\d.]+)(k|m|b|万|亿)/);
  if (compact) {
    const amount = Number(compact[1]);
    if (!Number.isFinite(amount)) return null;

    switch (compact[2]) {
      case 'k':
        return Math.round(amount * 1_000);
      case 'm':
        return Math.round(amount * 1_000_000);
      case 'b':
        return Math.round(amount * 1_000_000_000);
      case '万':
        return Math.round(amount * 10_000);
      case '亿':
        return Math.round(amount * 100_000_000);
      default:
        return null;
    }
  }

  const firstNumber = normalized.match(/(\d[\d.]*)/);
  if (!firstNumber) return null;
  const parsed = Number(firstNumber[1]);
  return Number.isFinite(parsed) ? Math.round(parsed) : null;
}
